{
    "openapi": "3.0.0",
    "info": {
        "title": "Team Management Api",
        "summary": "A teams and projects management api",
        "description": "A back-end application for managing teams, employees and projects.",
        "version": "1.0.0"
      },
      "servers" : [
        {
            "url": "https://team-management-0br5.onrender.com/",
            "description": "Render Deploy"
        },
        {
            "url": "http://localhost:3000",
            "description": "localhost"
        }
        
      ],
      "paths":{
        "/employee": {
            "get":{
                "summary": "Gets a list of all employees",
                "description": "This endpoint gets a list of all employees registered in the database and their data",
                "tags": ["Employees"],
                "responses": {
                    "200":{
                        "description" : "A list of all employees",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {"$ref": "#components/schemas/Employee"}
                                }
                            }
                        }
                    }
                }
            },
            "post":{
                "summary": "Creates a new employee",
                "description": "This endpoint creates a new employee in the database with their given data",
                "tags": ["Employees"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "properties": {
                                    "first_name": {
                                        "type": "string"
                                    },
                                    "last_name": {
                                        "type": "string"
                                    },
                                    "birth_year": {
                                        "type": "number"
                                    },
                                    "monthly_salary": {
                                        "type": "number"
                                    },
                                    "seniority": {
                                        "type": "string"
                                    },
                                    "specialty": {
                                        "type": "string"
                                    }
                                }
                            }, 
                            "examples": {
                                "employee": {
                                    "value":  {
                                        "first_name": "Jos√©",
                                        "last_name": "Da Silva",
                                        "birth_year": 1989,
                                        "monthly_salary": 12000,
                                        "seniority": "senior",
                                        "specialty": "Quality Assurance"
                                      }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deletes an employee",
                "description": "This endpoint deletes the employee that has the given id",
                "tags": ["Employees"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "properties": {
                                    "employee_id": {
                                        "type": "string"
                                    }
                                }
                            }, 
                            "examples": {
                                "employee": {
                                    "value":  {
                                        "employee_id": "(id of an existing employee)"
                                      }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Updates an employee's data",
                "description": "This endpoint updates an employee's information in the database with the new given data",
                "tags": ["Employees"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "type": "object",
                                "properties": {
                                    "employee_id": {"type":"string"},
                                    "employee":{
                                        "type": "object",
                                        "properties":{
                                            "first_name": {
                                                "type": "string"
                                            },
                                            "last_name": {
                                                "type": "string"
                                            },
                                            "birth_year": {
                                                "type": "number"
                                            },
                                            "monthly_salary": {
                                                "type": "number"
                                            },
                                            "seniority": {
                                                "type": "string"
                                            },
                                            "specialty": {
                                                "type": "string"
                                            }
                                        }
                                        
                                    }
                                }
                            },
                            "examples":{
                                "example id":  {
                                    "value": {"employee_id":"(id of an existing employee)"}
                                  }
                            }
                            
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
        },
        "/employee/search/{id}": {
            "get":{
                "summary": "Gets a single employee's details",
                "description": "This endpoint gets a single employee's data and a list of projects to wich he is appointed to",
                "tags": ["Employees"],
                "parameters":[
                    {
                        "name": "id",
                        "in": "path",
                        "description": "The id of the employee that is being searched",
                        "required": "true"
                    }
                ],
                "responses": {
                    "200":{
                        "description" : "An employee's details and his projects",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties":{
                                        "employee_data":{"$ref": "#components/schemas/Employee"},
                                        "allocated_projects": {
                                            "type": "array",
                                            "items": {"$ref": "#components/schemas/AllocatedProject"}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/project": {
            "get":{
                "summary": "Gets a list of all projects",
                "description": "This endpoint gets a list of all projects registered in the database and their data",
                "tags": ["Projects"],
                "responses": {
                    "200":{
                        "description" : "A list of all projects",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {"$ref": "#components/schemas/Project"}
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Creates a new project",
                "description": "This endpoint creates a new employee in the database with their given data",
                "tags": ["Projects"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "properties": {
                                    "name": {"type": "string"},
                                    "description": {"type": "string"},
                                    "role": {"type": "string"},
                                    "start_date": {"type": "string"},
                                    "end_date": {"type": "string"},
                                    "manager_id": {"type": "string"}
                                }
                            }, 
                            "examples": {
                                "employee": {
                                    "value":  {
                                        "name": "New features on weather app",
                                        "description": "Develop and launch the features that will be released on the upcoming update.",
                                        "start_date": "2024-03-04T00:00:00.000Z",
                                        "due_date": "2024-10-15T00:00:00.000Z",
                                        "status": "Planning",
                                        "manager_id": null
                                      }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put":{
                "summary": "Updates a project's data",
                "description": "This endpoint updates a project's information in the database with the new given data",
                "tags": ["Projects"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "type": "object",
                                "properties": {
                                    "project_id": {"type":"string"},
                                    "project":{
                                        "type": "object",
                                        "properties":{
                                            "name":{"type": "string"},
                                            "description": {"type": "string"},
                                            "start_date": {"type": "string"},
                                            "due_date": {"type": "string"},
                                            "status": {"type": "string"},
                                            "manager_id": {"type": "string", "required": "false"}
                                        }
                                        
                                    }
                                }
                            },
                            "examples":{
                                "example":  {
                                    "value": {
                                        "project_id": "bd5f3edf-301b-4b1b-a272-053e8fca1ee5",
                                        "project":{
                                                "name": "Updates Project Name",
                                                "description": "New project description",
                                                "start_date": "10-10-2026",
                                                "due_date": "10-10-2027",
                                                "status": "Planning"
                                         }
                                    }
                                  }
                            }
                            
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
            "summary": "Deletes a project",
            "description": "This endpoint deletes the project that has the given id from the database",
            "tags": ["Projects"],
            "requestBody": {
                "content":{
                    "application/json": {
                        "schema": { 
                            "properties": {
                                "project_id": {
                                    "type": "string"
                                }
                            }
                        }, 
                        "examples": {
                            "employee": {
                                "value":  {
                                    "employee_id": "(id of an existing employee)"
                                  }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description" : "Sucess message",
                    "content":{
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "message": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "patch": {
            "summary": "Changes a project's current manager",
            "description": "This endpoint updates the manager of a project that has the given id",
            "tags": ["Projects"],
            "requestBody": {
                "content":{
                    "application/json": {
                        "schema": { 
                            "properties": {
                                "project_id": {
                                    "type": "string"
                                },
                                "manager_id": {
                                    "type": "string"
                                }
                            }
                        }, 
                        "examples": {
                            "example": {
                                "value":  {
                                    "project_id": "089d6001-b485-4946-8737-1f150d4ef11d",
                                    "manager_id": "351a21f0-35ca-4c6e-9bbe-98714e964a97"
                                  }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description" : "Sucess message",
                    "content":{
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "message": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        },
        "/allocation":{
            "get": {
                "summary": "Gets a list of all allocations",
                "description": "This endpoint gets a list of all allocations registered in the database",
                "tags": ["Allocations"],
                "responses": {
                    "200":{
                        "description" : "A list of all allocations",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {"$ref": "#components/schemas/Allocation"}
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Creates an allocation",
                "description": "This endpoint allocates a project to an employee in the database",
                "tags": ["Allocations"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "type" : "#components/schemas/Allocation"
                            }, 
                            "examples": {
                                "example": {
                                    "value":  {
                                        "project_id": "892eef7e-372f-4b38-8c4b-25374307042a",
                                        "employee_id": "d72d3edc-64e1-43c9-b839-103f284bdcab",
                                        "role": "Marketing Specialist",
                                        "start_date": "2023-03-01T00:00:00.000Z",
                                        "end_date": "2023-10-12T00:00:00.000"
                                      }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {"type":"string"}
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deletes an allocation",
                "description": "This endpoint deletes an allocation in the database",
                "tags": ["Allocations"],
                "requestBody": {
                    "content":{
                        "application/json": {
                            "schema": { 
                                "type" : "object",
                                "properties":{
                                    "project_id": {"type": "string"},
                                    "employee_id":{"type": "string"}
                                }
                            }, 
                            "examples": {
                                "example": {
                                    "value":  {
                                        "project_id": "892eef7e-372f-4b38-8c4b-25374307042a",
                                        "employee_id": "d72d3edc-64e1-43c9-b839-103f284bdcab"
                                      }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description" : "Sucess message",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {"type":"string"}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
      },
      "components": {
        "schemas": {
            "Employee":{
                "type": "object",
                "properties": {
                    "employee_id": {"type": "string"},
                    "first_name": {"type": "string"},
                    "last_name": {"type": "string"},
                    "birth_year": {"type": "string"},
                    "monthly_salary": {"type": "number"},
                    "specialty": {"type": "string"},
                    "seniority": {"type": "string"}
                }
            },
            "AllocatedProject":{
                "type": "object",
                "properties": {
                    "project_id": {"type": "string"},
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "role": {"type": "string"},
                    "start_date": {"type": "string"},
                    "end_date": {"type": "string"}
                }
            },
            "Project":{
                "type": "object",
                "properties": {
                    "project_id": {"type": "string"},
                    "name":{"type": "string"},
                    "description": {"type": "string"},
                    "start_date": {"type": "string"},
                    "due_date": {"type": "string"},
                    "status": {"type": "string"},
                    "manager_id": {"type": "string"}
                }
            },
            "Allocation": {
                "project_id": {"type": "string"},
                "employee_id": {"type": "string"},
                "role": {"type": "string"},
                "start_date": {"type": "string"},
                "end_date": {"type": "string"}
            }

        }
      }
    }
      
